version: '3.7'
services:
    chrome:
        image: selenium/standalone-chrome:latest
        hostname: chrome
        networks:
            - airflownet
    web:
        build: 
          context: ./services/web
          dockerfile: Dockerfile.amd
        command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        ports:
            - 8000:8000
        expose:
          - 8000
        env_file:
          - ./services/web/.env
        depends_on: 
          - db
        volumes:
          - .:/usr/src/app
        networks:
            - airflownet
    db:
        image: postgres:12.0
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=test_db
        networks:
            - airflownet
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
          - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
          - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
          - "5050:80"
        depends_on:
          - db   
        networks:
            - airflownet
    postgres-airflow:
        image: postgres
        environment: 
          POSTGRES_PASSWORD: pssd
          POSTGRES_USER: airflowuser
          POSTGRES_DB: airflowdb
          AIRFLOW_SCHEMA: airflow
        ports:
          - "5433:5433"
        expose:
          - 5433
        restart: always
        volumes:
          - ./services/airflow/scripts_postgres:/docker-entrypoint-initdb.d
        command: -p 5433 #change port Postgres is running on
        networks:
          - airflownet
    airflow:
      build: 
        context: ./services/airflow
        dockerfile: Dockerfile.amd
      restart: always
      environment: 
        DBT_PROFILES_DIR: /services/airflow/dbt
        AIRFLOW_HOME: /services/airflow/airflow
        AIRFLOW__CORE__DAGS_FOLDER: /services/airflow/airflow/dags
        AIRFLOW__CORE__PARALLELISM: 4
        AIRFLOW__CORE__DAG_CONCURRENCY: 4
        AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 4
        POSTGRES_USER: airflowuser
        POSTGRES_PASSWORD: pssd
        POSTGRES_HOST: postgres-airflow
        POSTGRES_PORT: 5433
        POSTGRES_DB: airflowdb
        DBT_POSTGRES_PASSWORD: postgres
        DBT_POSTGRES_USER: postgres
        DBT_POSTGRES_DB: postgres
        DBT_DBT_SCHEMA: test
        DBT_DBT_RAW_DATA_SCHEMA: public
        DBT_POSTGRES_HOST: db
        MY_USERNAME: maxence
        MY_PASSWORD: maxence
      depends_on: 
        - postgres-airflow
        - statsd-exporter
      ports:
        - 7777:8080
      volumes: 
        - ./services/airflow/dbt:/services/airflow/dbt
        - ./services/airflow/airflow:/services/airflow/airflow
      networks:
        - airflownet
    statsd-exporter:
        image: prom/statsd-exporter
        container_name: airflow-statsd-exporter
        command: "--statsd.listen-udp=:8125 --web.listen-address=:9102"
        ports:
            - 9123:9102
            - 8125:8125/udp
        networks:
            - airflownet
    # prometheus:
    #     image: prom/prometheus
    #     container_name: airflow-prometheus
    #     user: "0"
    #     ports:
    #         - 9090:9090
    #     volumes:
    #         - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    #         - ./services/prometheus/volume:/prometheus
    #     networks:
    #         - airflownet
    # grafana:
    #     image: grafana/grafana:7.1.5
    #     container_name: airflow-grafana
    #     environment:
    #         GF_SECURITY_ADMIN_USER: admin
    #         GF_SECURITY_ADMIN_PASSWORD: password
    #         GF_PATHS_PROVISIONING: /grafana/provisioning
    #     ports:
    #         - 3000:3000
    #     volumes:
    #         - ./services/grafana/volume/data:/grafana
    #         - ./services/grafana/volume/datasources:/grafana/datasources
    #         - ./services/grafana/volume/dashboards:/grafana/dashboards
    #         - ./services/grafana/volume/provisioning:/grafana/provisioning
    #     networks:
    #         - airflownet

volumes:
    postgres_data:
networks:
    airflownet:
      driver: bridge
    