version: '3.7'
services:
    chrome:
        image: kynetiv/selenium-standalone-chromium-pi
        hostname: chrome
        networks:
            - airflownet
    web:
        command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        ports:
            - 8000:8000
        expose:
          - 8000
        env_file:
          - .env
        depends_on:
          - db
        volumes:
          - .:/usr/src/app
        networks:
            - airflownet
        image: maxenceroux/spotify_web:latest

    db:
        image: arm32v7/postgres
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=test_db
        networks:
            - airflownet
    pgadmin:
        container_name: pgadmin
        image: biarms/pgadmin4
        environment:
          - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
          - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
          - "5050:5050"
        depends_on:
          - db   
        networks:
            - airflownet
    postgres-airflow:
        image: arm32v7/postgres
        environment: 
          POSTGRES_PASSWORD: pssd
          POSTGRES_USER: airflowuser
          POSTGRES_DB: airflowdb
          AIRFLOW_SCHEMA: airflow
        ports:
          - "5433:5433"
        expose:
          - 5433
        restart: always
        volumes:
          - ./services/airflow/scripts_postgres:/docker-entrypoint-initdb.d
        command: -p 5433 #change port Postgres is running on
        networks:
          - airflownet
    airflow:
      restart: always
      env_file:
        - .env
      depends_on: 
        - postgres-airflow
      ports:
        - 7777:8080
      volumes: 
        - ./services/airflow/dbt:/services/airflow/dbt
        - ./services/airflow/airflow:/services/airflow/airflow
      networks:
        - airflownet
      image: maxenceroux/airflow-rpi:latest
    statsd-exporter:
        image: prom/statsd-exporter
        container_name: airflow-statsd-exporter
        command: "--statsd.listen-udp=:8125 --web.listen-address=:9102"
        ports:
            - 9123:9102
            - 8125:8125/udp
        networks:
            - airflownet
volumes:
  postgres_data:
networks:
  airflownet:
    driver: bridge