"""First migration

Revision ID: 32e05b5e907e
Revises: abbfcd8b16c0
Create Date: 2021-01-29 09:07:38.283299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32e05b5e907e'
down_revision = 'abbfcd8b16c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('spotify_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listen_id'), 'listen', ['id'], unique=False)
    op.add_column('song', sa.Column('acousticness', sa.Float(), nullable=True))
    op.add_column('song', sa.Column('added_at', sa.DateTime(), nullable=True))
    op.add_column('song', sa.Column('danceability', sa.Float(), nullable=True))
    op.add_column('song', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('song', sa.Column('energy', sa.Float(), nullable=True))
    op.add_column('song', sa.Column('instrumentalness', sa.Float(), nullable=True))
    op.add_column('song', sa.Column('key', sa.Integer(), nullable=True))
    op.add_column('song', sa.Column('liveness', sa.Float(), nullable=True))
    op.add_column('song', sa.Column('loudness', sa.Float(), nullable=True))
    op.add_column('song', sa.Column('mode', sa.Integer(), nullable=True))
    op.add_column('song', sa.Column('speechiness', sa.Float(), nullable=True))
    op.add_column('song', sa.Column('tempo', sa.Float(), nullable=True))
    op.add_column('song', sa.Column('valence', sa.Float(), nullable=True))
    op.drop_column('song', 'ts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('song', 'valence')
    op.drop_column('song', 'tempo')
    op.drop_column('song', 'speechiness')
    op.drop_column('song', 'mode')
    op.drop_column('song', 'loudness')
    op.drop_column('song', 'liveness')
    op.drop_column('song', 'key')
    op.drop_column('song', 'instrumentalness')
    op.drop_column('song', 'energy')
    op.drop_column('song', 'duration')
    op.drop_column('song', 'danceability')
    op.drop_column('song', 'added_at')
    op.drop_column('song', 'acousticness')
    op.drop_index(op.f('ix_listen_id'), table_name='listen')
    op.drop_table('listen')
    # ### end Alembic commands ###
