# pull official base image
FROM arm32v7/python:3.8
# FROM python:3.8
# set work directory
WORKDIR /usr/src/app/

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# install dependencies
COPY ./requirements.txt /usr/src/app/requirements.txt

RUN pip3 install -r requirements.txt
WORKDIR /usr/src/app/services/web
# copy project
COPY . /usr/src/app/